### PR TITLE
Feature/ui

### PR DESCRIPTION
**Pull request by Rayhan1998**
Added some responsiveness to movie box and added an input hover feature.

### CODE REVIEW

**Comment by Rayhan1998** [comment]
a

**Comment by Rayhan1998** [comment]
Thats odd I did a pull before pushing. Maybe because I removed some of the merge conflicts. I will try again.

**Comment by Rayhan1998** [comment]
Changed some naming on input. Also I'm not sure how to set transition only with chakara. I will need help with that.

**Comment by cgefx** [comment]
```
<InputGroup 
        width={isHover ? '50%' : '45%'} 
        transition="0.5s" 
        size="lg"
      >
```

**Comment by Rayhan1998** [comment]
Okay, I see. Did not know chakra accepted transition as a prop.

**Pull request merged**
