### PR TITLE
Feature/create list

### PR DESCRIPTION
**Pull request by BFrancoeur**

### CODE REVIEW

**Comment by cgefx** [comment]
A few things here

1 - this PR is attempting to merge into master.   At the top of the page see:

-  "BFrancoeur wants to merge 17 commits into master from feature/create-list"

when making a feature branch PR you need to change master to development.  

2 -  the CreateListForm.js file exposes the firebase API key. this is unnecessary (and dangerous) as firebase is already initialized in firebase/firebase.js 

3 -  our agreed upon component naming is ComponentName/index.js.  Please see the rest of the project structure. 

4 -  handleSubmit is pushing data to the realtime database - the app is configured to use cloud  firestore.  It looks like the realtime database is now causing issues with the firestore. ill look into whats going on. 

Lemme know if you have questions on any of this.

**Comment by BFrancoeur** [comment]
Hi @cgefx -- I'm a bit confused here. I selected the development branch before making the PR. I'm not sure what I'm doing wrong.

**Comment by cgefx** [comment]
if you clicked "edit" and changed master to development in the dropdown, perhaps you didn't click "save" before opening up the PR?

**Comment by BFrancoeur** [comment]
Hmmm...I didn't click 'save'. That's what I've been missing. Thank you for pointing that out :)

**Pull request closed without merging**
